### ISSUE TITLE
Data more than 28 days

### ISSUE THREAD

**Issue by vinaysandela** [github-copilot-resources/copilot-metrics-viewer#102] opened 2024-10-10 19:51 UTC
We are using this for getting metrics at our Organization.  The present data is from last 28 days. 
Can you please help in getting data right from the time we enabled Copilot? or a way to increase the days?

Thankss

**Comment by karpikpl** [comment] 2024-10-19 01:38
duplicate of #15

**Closed by karpikpl** 2024-10-19 01:38 UTC
